export const queryKeys = {
  authSession: () => ["auth", "session"] as const,
  simulationStatus: () => ["simulation", "status"] as const,
  simulationState: () => ["simulation", "state"] as const,
  simulationSettings: () => ["simulation", "settings"] as const,
  simulationList: () => ["simulation", "list"] as const,
  simulationPlayers: () => ["simulation", "players"] as const,
  economicIndicators: () => ["economic-indicators"] as const,
  fixedIncomeList: () => ["fixed-income", "list"] as const,
  fixedIncomeAsset: (id: string) => ["fixed-income", id] as const,
  fixedIncomeProjection: (id: string, amount: string, currentDate: string) =>
    ["fixed-income", id, "projection", amount, currentDate] as const,
  variableIncomeList: () => ["variable-income", "list"] as const,
  variableIncomeStock: (ticker: string) => ["variable-income", ticker] as const,
  variableIncomeOrders: (ticker: string) => ["variable-income", ticker, "orders"] as const,
  portfolio: () => ["portfolio"] as const,
  patrimonialHistory: () => ["portfolio", "history"] as const,
  portfolioPosition: (ticker: string) => ["portfolio", ticker] as const,
  portfolioCash: () => ["portfolio", "cash"] as const,
  statistics: () => ["statistics"] as const,
  statisticsReport: (tab: string, simulationIds: number[]) => ["statistics", tab, ...simulationIds] as const,
  correlationAssets: () => ["correlation", "assets"] as const,
  correlation: (tickers: string[], window: string, end: string | null) =>
    ["correlation", window, end, ...tickers] as const,
  notificationSettings: () => ["notifications", "settings"] as const,
  seriesCoverage: () => ["import-assets", "coverage"] as const,
  sectors: () => ["import-assets", "sectors"] as const,
  tunnelStatus: () => ["tunnel", "status"] as const,
} as const;
