/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/variable-income": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar ativos de renda variável
         * @description Retorna a lista de todos os ativos de renda variável (ações) disponíveis na simulação.
         */
        get: operations["get_variable_income_api_variable_income_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/variable-income/{asset}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter detalhes de um ativo
         * @description Retorna as informações detalhadas de um ativo de renda variável específico.
         */
        get: operations["get_variable_income_details_api_variable_income__asset__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/variable-income/{asset}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar ordens do livro
         * @description Lista todas as ordens ativas (BUY + SELL) no livro de ordens para o ativo especificado.
         */
        get: operations["list_order_book_api_variable_income__asset__orders_get"];
        put?: never;
        /**
         * Submeter ordem de compra/venda
         * @description Cria e submete uma nova ordem (MARKET ou LIMIT) para o ativo especificado.
         */
        post: operations["submit_order_api_variable_income__asset__orders_post"];
        /**
         * Cancelar ordem
         * @description Remove uma ordem ativa do livro de ordens para o ativo informado.
         */
        delete: operations["cancel_order_api_variable_income__asset__orders_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fixed-income": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar ativos de renda fixa
         * @description Retorna a lista de todos os ativos de renda fixa disponíveis na simulação.
         */
        get: operations["get_fixed_income_api_fixed_income_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fixed-income/{asset_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter detalhes de renda fixa
         * @description Retorna as informações detalhadas de um ativo de renda fixa específico.
         */
        get: operations["get_fixed_income_details_api_fixed_income__asset_uuid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fixed-income/{asset_uuid}/buy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Comprar ativo de renda fixa
         * @description Realiza a compra de um ativo de renda fixa com a quantidade especificada.
         */
        post: operations["buy_fixed_income_api_fixed_income__asset_uuid__buy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter portfólio
         * @description Retorna o portfólio atual do cliente com todas as posições e saldos.
         */
        get: operations["get_portfolio_api_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/cash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter saldo em caixa
         * @description Retorna o saldo de caixa (dinheiro disponível) do cliente.
         */
        get: operations["get_cash_api_portfolio_cash_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter posição de um ativo
         * @description Retorna as informações de posição (quantidade, preço médio, etc.) de um ativo específico no portfólio.
         */
        get: operations["get_portfolio_ticker_api_portfolio__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter configurações do usuário
         * @description Retorna as configurações pessoais do usuário (notificações de ordens, etc.).
         */
        get: operations["get_settings_api_settings_get"];
        /**
         * Atualizar configurações do usuário
         * @description Atualiza as configurações pessoais do usuário.
         */
        put: operations["update_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import-assets/yfinance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Importar dados de yfinance
         * @description Importa dados de ativos do yfinance para um ticker especificado.
         */
        post: operations["import_assets_json_api_import_assets_yfinance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import-assets/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Importar dados de CSV
         * @description Importa dados de ativos a partir de um arquivo CSV enviado via multipart/form-data.
         */
        post: operations["import_assets_csv_api_import_assets_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream de eventos SSE
         * @description Retorna um stream de eventos em tempo real via Server-Sent Events (SSE).
         */
        get: operations["stream_api_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/update-subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Atualizar inscrição de eventos
         * @description Atualiza a lista de eventos em tempo real que o cliente deseja receber.
         */
        post: operations["update_subscription_api_update_subscription_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/set-speed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Definir velocidade da simulação
         * @description Ajusta a velocidade de execução da simulação (0 para pausar, valores maiores para acelerar).
         */
        post: operations["set_speed_api_set_speed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/get-simulation-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter estado da simulação
         * @description Retorna o estado atual da simulação incluindo data, velocidade e saldo do cliente.
         */
        get: operations["get_simulation_state_api_get_simulation_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inicializa a sessão
         * @description Garante que o cliente possua um client_id persistido no cookie. Se já existir, retorna o existente. Se não existir, cria um novo e salva no cookie.
         */
        post: operations["session_init_api_session_init_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter dados da sessão
         * @description Retorna as informações da sessão atual do cliente autenticado.
         */
        get: operations["session_me_api_session_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout do cliente
         * @description Encerra a sessão removendo a presença do cliente e invalidando o cookie de autenticação.
         */
        post: operations["session_logout_api_session_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar novo usuário
         * @description Cria um novo usuário com o nickname fornecido para o client_id atual. Se houver simulação ativa, concede o depósito inicial.
         */
        post: operations["user_register_api_user_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recuperar usuário existente
         * @description Permite recuperar um usuário existente pelo nickname após limpar o navegador ou trocar de dispositivo.
         */
        post: operations["user_claim_api_user_claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Deletar usuário
         * @description Remove permanentemente o usuário atual e todos os dados relacionados (em cascata).
         */
        delete: operations["user_delete_api_user_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter estatísticas de desempenho
         * @description Retorna o histórico de desempenho de todos os jogadores da simulação.
         */
        get: operations["get_statistics_api_statistics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/economic-indicators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter indicadores econômicos
         * @description Retorna os indicadores econômicos da simulação atual.
         */
        get: operations["get_economic_indicators_api_economic_indicators_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter status da simulação
         * @description Retorna o status atual da simulação (ativa ou inativa) e seus parâmetros.
         */
        get: operations["simulation_status_api_simulation_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Criar nova simulação
         * @description Cria e inicia uma nova simulação com os parâmetros fornecidos (datas, capital inicial, contribuição mensal).
         */
        post: operations["create_simulation_api_simulation_create_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation/continue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Continuar simulação
         * @description Continua uma simulação anterior a partir do último snapshot salvo até a nova data de término.
         */
        post: operations["continue_simulation_api_simulation_continue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parar simulação
         * @description Encerra a simulação atual manualmente.
         */
        post: operations["stop_simulation_api_simulation_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar jogadores ativos
         * @description Retorna a lista de todos os usuários ativos na simulação atual.
         */
        get: operations["get_active_players_api_simulation_players_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter configurações da simulação
         * @description Retorna as configurações da simulação atual e indica se o usuário é o host.
         */
        get: operations["get_simulation_settings_api_simulation_settings_get"];
        /**
         * Atualizar configurações da simulação
         * @description Atualiza os parâmetros da simulação (datas, capital, contribuição mensal). Apenas o host pode executar.
         */
        put: operations["update_simulation_settings_api_simulation_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tunnel/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar túnel
         * @description Inicia o túnel de rede para exposição da API (apenas o host pode executar).
         */
        post: operations["start_tunnel_api_tunnel_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tunnel/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parar túnel
         * @description Encerra o túnel de rede (apenas o host pode executar).
         */
        post: operations["stop_tunnel_api_tunnel_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tunnel/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter status do túnel
         * @description Retorna o status atual do túnel (ativo/inativo, URL, provider configurado).
         */
        get: operations["get_tunnel_status_api_tunnel_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_import_assets_csv_api_import_assets_csv_post */
        Body_import_assets_csv_api_import_assets_csv_post: {
            /** Ticker */
            ticker: string;
            /** Csv File */
            csv_file: string;
            /**
             * Overwrite
             * @default false
             */
            overwrite: string;
        };
        /** BuyFixedIncomeRequest */
        BuyFixedIncomeRequest: {
            /** Quantity */
            quantity: number;
        };
        /** CancelOrderRequest */
        CancelOrderRequest: {
            /** Order Id */
            order_id: string;
        };
        /** CandleDTO */
        CandleDTO: {
            /** Id */
            id: number;
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Volume */
            volume: number;
            /**
             * Price Date
             * Format: date
             */
            price_date: string;
            /** Change */
            change: number;
            /** Change Pct */
            change_pct: string;
        };
        /** CashResponse */
        CashResponse: {
            /** Cash */
            cash: number;
        };
        /** ContinueSimulationRequest */
        ContinueSimulationRequest: {
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Starting Cash */
            starting_cash: number;
            /**
             * Monthly Contribution
             * @default 0
             */
            monthly_contribution: number;
        };
        /** CreateSimulationRequest */
        CreateSimulationRequest: {
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Starting Cash */
            starting_cash: number;
            /**
             * Monthly Contribution
             * @default 0
             */
            monthly_contribution: number;
        };
        /** EconomicIndicatorsDTO */
        EconomicIndicatorsDTO: {
            /** Ipca */
            ipca: number;
            /** Selic */
            selic: number;
            /** Cdi */
            cdi: number;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Message */
            message: string;
        };
        /** FixedIncomeAssetDTO */
        FixedIncomeAssetDTO: {
            /**
             * Asset Uuid
             * Format: uuid
             */
            asset_uuid?: string;
            /** Name */
            name: string;
            /** Issuer */
            issuer: string;
            investment_type: components["schemas"]["FixedIncomeType"];
            rate_index: components["schemas"]["RateIndexType"];
            /**
             * Maturity Date
             * Format: date
             */
            maturity_date: string;
            /** Interest Rate */
            interest_rate: number;
        };
        /** FixedIncomePositionDTO */
        FixedIncomePositionDTO: {
            asset: components["schemas"]["FixedIncomeAssetDTO"];
            /** Total Applied */
            total_applied: number;
            /** Current Value */
            current_value: number;
            /**
             * First Applied Date
             * Format: date
             */
            first_applied_date: string;
        };
        /**
         * FixedIncomeType
         * @enum {string}
         */
        FixedIncomeType: "CDB" | "LCI" | "LCA" | "Tesouro Direto";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportYFinanceRequest */
        ImportYFinanceRequest: {
            /** Ticker */
            ticker: string;
            /**
             * Overwrite
             * @default false
             */
            overwrite: boolean;
        };
        /**
         * OrderAction
         * @enum {string}
         */
        OrderAction: "buy" | "sell";
        /** OrderDTO */
        OrderDTO: {
            /** Id */
            id: string;
            /** Player Nickname */
            player_nickname: string;
            action: components["schemas"]["OrderAction"];
            order_type: components["schemas"]["OrderType"];
            status: components["schemas"]["OrderStatus"];
            /** Size */
            size: number;
            /** Remaining */
            remaining: number;
            /** Limit Price */
            limit_price: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** OrderNotificationSettings */
        OrderNotificationSettings: {
            /** Executed */
            executed: boolean;
            /** Partial */
            partial: boolean;
        };
        /**
         * OrderStatus
         * @enum {string}
         */
        OrderStatus: "executed" | "partial" | "pending" | "canceled";
        /**
         * OrderType
         * @enum {string}
         */
        OrderType: "market" | "limit";
        /** PatrimonialHistoryDTO */
        PatrimonialHistoryDTO: {
            /**
             * Snapshot Date
             * Format: date
             */
            snapshot_date: string;
            /** Total Networth */
            total_networth: string;
            /** Total Equity */
            total_equity: string;
            /** Total Fixed */
            total_fixed: string;
            /** Total Cash */
            total_cash: string;
            /** Total Contribution */
            total_contribution: string;
        };
        /** PlayerHistoryDTO */
        PlayerHistoryDTO: {
            /** Player Nickname */
            player_nickname: string;
            /** Starting Cash */
            starting_cash: number;
            /** History */
            history: components["schemas"]["PatrimonialHistoryDTO"][];
        };
        /** PlayerNickname */
        PlayerNickname: {
            /** Nickname */
            nickname: string;
        };
        /** PortfolioDTO */
        PortfolioDTO: {
            /** Starting Cash */
            starting_cash: number;
            /** Cash */
            cash: number;
            /** Variable Income */
            variable_income: components["schemas"]["PositionDTO"][];
            /** Fixed Income */
            fixed_income: components["schemas"]["FixedIncomePositionDTO"][];
            /** Patrimonial History */
            patrimonial_history: components["schemas"]["PatrimonialHistoryDTO"][];
        };
        /** PositionDTO */
        PositionDTO: {
            /** Ticker */
            ticker: string;
            /** Size */
            size: number;
            /** Reserved */
            reserved: number;
            /** Total Cost */
            total_cost: number;
            /** Avg Price */
            avg_price: number;
        };
        /**
         * RateIndexType
         * @enum {string}
         */
        RateIndexType: "CDI" | "IPCA" | "SELIC" | "Prefixado";
        /** SessionDTO */
        SessionDTO: {
            /** Authenticated */
            authenticated: boolean;
            user: components["schemas"]["UserDTO"] | null;
        };
        /** SetSpeedRequest */
        SetSpeedRequest: {
            /**
             * Speed
             * @default 0
             */
            speed: number;
        };
        /** SetSpeedResponse */
        SetSpeedResponse: {
            /** Speed */
            speed: number;
        };
        /** SettingsRequest */
        SettingsRequest: {
            orders: components["schemas"]["OrderNotificationSettings"];
        } & {
            [key: string]: unknown;
        };
        /** SimulationDTO */
        SimulationDTO: {
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Starting Cash */
            starting_cash: number;
            /** Monthly Contribution */
            monthly_contribution: number;
        };
        /** SimulationSettingsResponse */
        SimulationSettingsResponse: {
            /** Is Host */
            is_host: boolean;
            simulation: components["schemas"]["SimulationDTO"];
        };
        /** SimulationStateResponse */
        SimulationStateResponse: {
            /** Current Date */
            current_date: string;
            /** Speed */
            speed: number;
            /** Cash */
            cash: number;
        };
        /** SimulationStatusResponse */
        SimulationStatusResponse: {
            /** Active */
            active: boolean;
            simulation?: components["schemas"]["SimulationDTO"] | null;
        };
        /** StockDetailsDTO */
        StockDetailsDTO: {
            /** Id */
            id: number;
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Volume */
            volume: number;
            /**
             * Price Date
             * Format: date
             */
            price_date: string;
            /** Change */
            change: number;
            /** Change Pct */
            change_pct: string;
            /** History */
            history: components["schemas"]["StockPriceHistoryDTO"][];
        };
        /** StockPriceHistoryDTO */
        StockPriceHistoryDTO: {
            /**
             * Price Date
             * Format: date
             */
            price_date: string;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Volume */
            volume: number;
        };
        /** SubmitOrderRequest */
        SubmitOrderRequest: {
            /** Quantity */
            quantity: number;
            /** Type */
            type: string;
            /** Action */
            action: string;
            /** Limit Price */
            limit_price?: number | null;
        };
        /** SubmitOrderResponse */
        SubmitOrderResponse: {
            /** Order Id */
            order_id: string;
            /** Status */
            status: string;
        };
        /** TunnelStatusDTO */
        TunnelStatusDTO: {
            /** Active */
            active: boolean;
            /** Url */
            url: string | null;
            /** Provider */
            provider: string | null;
        };
        /** UpdateSettingsRequest */
        UpdateSettingsRequest: {
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Starting Cash */
            starting_cash: number;
            /**
             * Monthly Contribution
             * @default 0
             */
            monthly_contribution: number;
        };
        /** UpdateSubscriptionRequest */
        UpdateSubscriptionRequest: {
            /**
             * Events
             * @default []
             */
            events: string[];
        };
        /** UpdateSubscriptionResponse */
        UpdateSubscriptionResponse: {
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /** Events */
            events: string[];
        };
        /** UserClaimRequest */
        UserClaimRequest: {
            /** Nickname */
            nickname: string;
        };
        /** UserDTO */
        UserDTO: {
            /** Id */
            id: number;
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /** Nickname */
            nickname: string;
        };
        /** UserRegisterRequest */
        UserRegisterRequest: {
            /** Nickname */
            nickname: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_variable_income_api_variable_income_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandleDTO"][];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_variable_income_details_api_variable_income__asset__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockDetailsDTO"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_order_book_api_variable_income__asset__orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    submit_order_api_variable_income__asset__orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitOrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancel_order_api_variable_income__asset__orders_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_fixed_income_api_fixed_income_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixedIncomeAssetDTO"][];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_fixed_income_details_api_fixed_income__asset_uuid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixedIncomeAssetDTO"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    buy_fixed_income_api_fixed_income__asset_uuid__buy_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuyFixedIncomeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_portfolio_api_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioDTO"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_cash_api_portfolio_cash_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_portfolio_ticker_api_portfolio__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsRequest"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsRequest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    import_assets_json_api_import_assets_yfinance_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportYFinanceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    import_assets_csv_api_import_assets_csv_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_assets_csv_api_import_assets_csv_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    stream_api_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_subscription_api_update_subscription_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSubscriptionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateSubscriptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    set_speed_api_set_speed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetSpeedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetSpeedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_simulation_state_api_get_simulation_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationStateResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    session_init_api_session_init_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    session_me_api_session_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDTO"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    session_logout_api_session_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    user_register_api_user_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    user_claim_api_user_claim_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserClaimRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    user_delete_api_user_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_statistics_api_statistics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerHistoryDTO"][];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_economic_indicators_api_economic_indicators_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EconomicIndicatorsDTO"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    simulation_status_api_simulation_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationStatusResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_simulation_api_simulation_create_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSimulationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    continue_simulation_api_simulation_continue_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContinueSimulationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    stop_simulation_api_simulation_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_active_players_api_simulation_players_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerNickname"][];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_simulation_settings_api_simulation_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationSettingsResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_simulation_settings_api_simulation_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    start_tunnel_api_tunnel_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TunnelStatusDTO"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    stop_tunnel_api_tunnel_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_tunnel_status_api_tunnel_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TunnelStatusDTO"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
