import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import generatedApiSidebar from './docs/api/sidebar';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    { type: 'doc', id: 'intro', label: 'Introdução' },
    {
      type: 'category',
      label: 'Como Usar',
      items: [{ type: 'autogenerated', dirName: 'como-usar' }],
    },
    {
      type: 'category',
      label: 'Desenvolvimento',
      items: [{ type: 'autogenerated', dirName: 'desenvolvimento' }],
    },
  ],

  apisidebar: generatedApiSidebar,
};

export default sidebars;