import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Manual sidebar to ensure the top item is 'Introdução'
  tutorialSidebar: [
    { type: 'doc', id: 'intro', label: 'Introdução' },
    {
      type: 'category',
      label: 'Como Usar',
      items: [{ type: 'autogenerated', dirName: 'como-usar' }],
    },
    {
      type: 'category',
      label: 'Desenvolvimento',
      items: [{ type: 'autogenerated', dirName: 'desenvolvimento' }],
    },
  ],
};

export default sidebars;
